package cn.com.scal.components.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-10-18T16:19:32.077+08:00
 * Generated source version: 3.1.11
 * 
 */
@WebServiceClient(name = "OaWfWebService", 
                  wsdlLocation = "http://172.31.48.32/wfi/OaWfWebService.asmx?wsdl",
                  targetNamespace = "http://tempuri.org/") 
public class OaWfWebService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "OaWfWebService");
    public final static QName OaWfWebServiceSoap = new QName("http://tempuri.org/", "OaWfWebServiceSoap");
    public final static QName OaWfWebServiceSoap12 = new QName("http://tempuri.org/", "OaWfWebServiceSoap12");
    static {
        URL url = null;
        try {
            url = new URL("http://172.31.48.32/wfi/OaWfWebService.asmx?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(OaWfWebService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://172.31.48.32/wfi/OaWfWebService.asmx?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public OaWfWebService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OaWfWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OaWfWebService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public OaWfWebService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public OaWfWebService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public OaWfWebService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns OaWfWebServiceSoap
     */
    @WebEndpoint(name = "OaWfWebServiceSoap")
    public OaWfWebServiceSoap getOaWfWebServiceSoap() {
        return super.getPort(OaWfWebServiceSoap, OaWfWebServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OaWfWebServiceSoap
     */
    @WebEndpoint(name = "OaWfWebServiceSoap")
    public OaWfWebServiceSoap getOaWfWebServiceSoap(WebServiceFeature... features) {
        return super.getPort(OaWfWebServiceSoap, OaWfWebServiceSoap.class, features);
    }


    /**
     *
     * @return
     *     returns OaWfWebServiceSoap
     */
    @WebEndpoint(name = "OaWfWebServiceSoap12")
    public OaWfWebServiceSoap getOaWfWebServiceSoap12() {
        return super.getPort(OaWfWebServiceSoap12, OaWfWebServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OaWfWebServiceSoap
     */
    @WebEndpoint(name = "OaWfWebServiceSoap12")
    public OaWfWebServiceSoap getOaWfWebServiceSoap12(WebServiceFeature... features) {
        return super.getPort(OaWfWebServiceSoap12, OaWfWebServiceSoap.class, features);
    }

}
