package cn.com.scal.components.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-10-18T16:19:32.046+08:00
 * Generated source version: 3.1.11
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "OaWfWebServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface OaWfWebServiceSoap {

    @WebMethod(operationName = "BatchDeleteWFInstances", action = "http://tempuri.org/BatchDeleteWFInstances")
    @RequestWrapper(localName = "BatchDeleteWFInstances", targetNamespace = "http://tempuri.org/", className = "cn.com.scal.components.webservice.BatchDeleteWFInstances")
    @ResponseWrapper(localName = "BatchDeleteWFInstancesResponse", targetNamespace = "http://tempuri.org/", className = "cn.com.scal.components.webservice.BatchDeleteWFInstancesResponse")
    @WebResult(name = "BatchDeleteWFInstancesResult", targetNamespace = "http://tempuri.org/")
    public cn.com.scal.components.webservice.ArrayOfString batchDeleteWFInstances(
            @WebParam(name = "projectCode", targetNamespace = "http://tempuri.org/")
                    String projectCode,
            @WebParam(name = "userName", targetNamespace = "http://tempuri.org/")
                    String userName,
            @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
                    String password,
            @WebParam(name = "entitys", targetNamespace = "http://tempuri.org/")
                    cn.com.scal.components.webservice.ArrayOfWFInterfaceEntity2 entitys
    );

    @WebMethod(operationName = "UpdateWFInstanceStatusByInterfaceID", action = "http://tempuri.org/UpdateWFInstanceStatusByInterfaceID")
    @RequestWrapper(localName = "UpdateWFInstanceStatusByInterfaceID", targetNamespace = "http://tempuri.org/", className = "cn.com.scal.components.webservice.UpdateWFInstanceStatusByInterfaceID")
    @ResponseWrapper(localName = "UpdateWFInstanceStatusByInterfaceIDResponse", targetNamespace = "http://tempuri.org/", className = "cn.com.scal.components.webservice.UpdateWFInstanceStatusByInterfaceIDResponse")
    @WebResult(name = "UpdateWFInstanceStatusByInterfaceIDResult", targetNamespace = "http://tempuri.org/")
    public String updateWFInstanceStatusByInterfaceID(
            @WebParam(name = "projectCode", targetNamespace = "http://tempuri.org/")
                    String projectCode,
            @WebParam(name = "userName", targetNamespace = "http://tempuri.org/")
                    String userName,
            @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
                    String password,
            @WebParam(name = "interfaceID", targetNamespace = "http://tempuri.org/")
                    String interfaceID,
            @WebParam(name = "user_ID_Consigned", targetNamespace = "http://tempuri.org/")
                    String userIDConsigned,
            @WebParam(name = "user_Name_Consigned", targetNamespace = "http://tempuri.org/")
                    String userNameConsigned,
            @WebParam(name = "readTime", targetNamespace = "http://tempuri.org/")
                    String readTime,
            @WebParam(name = "finishTime", targetNamespace = "http://tempuri.org/")
                    String finishTime
    );

    @WebMethod(operationName = "GetUserOpinions", action = "http://tempuri.org/GetUserOpinions")
    @RequestWrapper(localName = "GetUserOpinions", targetNamespace = "http://tempuri.org/", className = "cn.com.scal.components.webservice.GetUserOpinions")
    @ResponseWrapper(localName = "GetUserOpinionsResponse", targetNamespace = "http://tempuri.org/", className = "cn.com.scal.components.webservice.GetUserOpinionsResponse")
    @WebResult(name = "GetUserOpinionsResult", targetNamespace = "http://tempuri.org/")
    public cn.com.scal.components.webservice.ArrayOfString getUserOpinions(
            @WebParam(name = "projectCode", targetNamespace = "http://tempuri.org/")
                    String projectCode,
            @WebParam(name = "userName", targetNamespace = "http://tempuri.org/")
                    String userName,
            @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
                    String password,
            @WebParam(name = "employeeID", targetNamespace = "http://tempuri.org/")
                    String employeeID
    );

    @WebMethod(operationName = "UpdateWFInstanceStatus3", action = "http://tempuri.org/UpdateWFInstanceStatus3")
    @RequestWrapper(localName = "UpdateWFInstanceStatus3", targetNamespace = "http://tempuri.org/", className = "cn.com.scal.components.webservice.UpdateWFInstanceStatus3")
    @ResponseWrapper(localName = "UpdateWFInstanceStatus3Response", targetNamespace = "http://tempuri.org/", className = "cn.com.scal.components.webservice.UpdateWFInstanceStatus3Response")
    @WebResult(name = "UpdateWFInstanceStatus3Result", targetNamespace = "http://tempuri.org/")
    public String updateWFInstanceStatus3(
            @WebParam(name = "projectCode", targetNamespace = "http://tempuri.org/")
                    String projectCode,
            @WebParam(name = "userName", targetNamespace = "http://tempuri.org/")
                    String userName,
            @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
                    String password,
            @WebParam(name = "instanceID", targetNamespace = "http://tempuri.org/")
                    String instanceID,
            @WebParam(name = "stepID", targetNamespace = "http://tempuri.org/")
                    String stepID,
            @WebParam(name = "user_ID_Consigned", targetNamespace = "http://tempuri.org/")
                    String userIDConsigned,
            @WebParam(name = "user_Name_Consigned", targetNamespace = "http://tempuri.org/")
                    String userNameConsigned,
            @WebParam(name = "readTime", targetNamespace = "http://tempuri.org/")
                    String readTime,
            @WebParam(name = "finishTime", targetNamespace = "http://tempuri.org/")
                    String finishTime,
            @WebParam(name = "newFormUrl", targetNamespace = "http://tempuri.org/")
                    String newFormUrl,
            @WebParam(name = "newMobileFormUrl", targetNamespace = "http://tempuri.org/")
                    String newMobileFormUrl,
            @WebParam(name = "newInternetFormUrl", targetNamespace = "http://tempuri.org/")
                    String newInternetFormUrl
    );

    @WebMethod(operationName = "UpdateWFInstanceStatus2", action = "http://tempuri.org/UpdateWFInstanceStatus2")
    @RequestWrapper(localName = "UpdateWFInstanceStatus2", targetNamespace = "http://tempuri.org/", className = "cn.com.scal.components.webservice.UpdateWFInstanceStatus2")
    @ResponseWrapper(localName = "UpdateWFInstanceStatus2Response", targetNamespace = "http://tempuri.org/", className = "cn.com.scal.components.webservice.UpdateWFInstanceStatus2Response")
    @WebResult(name = "UpdateWFInstanceStatus2Result", targetNamespace = "http://tempuri.org/")
    public String updateWFInstanceStatus2(
            @WebParam(name = "projectCode", targetNamespace = "http://tempuri.org/")
                    String projectCode,
            @WebParam(name = "userName", targetNamespace = "http://tempuri.org/")
                    String userName,
            @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
                    String password,
            @WebParam(name = "instanceID", targetNamespace = "http://tempuri.org/")
                    String instanceID,
            @WebParam(name = "stepID", targetNamespace = "http://tempuri.org/")
                    String stepID,
            @WebParam(name = "user_ID_Consigned", targetNamespace = "http://tempuri.org/")
                    String userIDConsigned,
            @WebParam(name = "user_Name_Consigned", targetNamespace = "http://tempuri.org/")
                    String userNameConsigned,
            @WebParam(name = "readTime", targetNamespace = "http://tempuri.org/")
                    String readTime,
            @WebParam(name = "finishTime", targetNamespace = "http://tempuri.org/")
                    String finishTime,
            @WebParam(name = "newFormUrl", targetNamespace = "http://tempuri.org/")
                    String newFormUrl
    );

    @WebMethod(operationName = "BatchUpdateWFInstances", action = "http://tempuri.org/BatchUpdateWFInstances")
    @RequestWrapper(localName = "BatchUpdateWFInstances", targetNamespace = "http://tempuri.org/", className = "cn.com.scal.components.webservice.BatchUpdateWFInstances")
    @ResponseWrapper(localName = "BatchUpdateWFInstancesResponse", targetNamespace = "http://tempuri.org/", className = "cn.com.scal.components.webservice.BatchUpdateWFInstancesResponse")
    @WebResult(name = "BatchUpdateWFInstancesResult", targetNamespace = "http://tempuri.org/")
    public cn.com.scal.components.webservice.ArrayOfString batchUpdateWFInstances(
            @WebParam(name = "projectCode", targetNamespace = "http://tempuri.org/")
                    String projectCode,
            @WebParam(name = "userName", targetNamespace = "http://tempuri.org/")
                    String userName,
            @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
                    String password,
            @WebParam(name = "entitys", targetNamespace = "http://tempuri.org/")
                    cn.com.scal.components.webservice.ArrayOfWFInterfaceEntity2 entitys
    );

    @WebMethod(operationName = "GetInterfaceEntity", action = "http://tempuri.org/GetInterfaceEntity")
    @RequestWrapper(localName = "GetInterfaceEntity", targetNamespace = "http://tempuri.org/", className = "cn.com.scal.components.webservice.GetInterfaceEntity")
    @ResponseWrapper(localName = "GetInterfaceEntityResponse", targetNamespace = "http://tempuri.org/", className = "cn.com.scal.components.webservice.GetInterfaceEntityResponse")
    @WebResult(name = "GetInterfaceEntityResult", targetNamespace = "http://tempuri.org/")
    public cn.com.scal.components.webservice.WFInterfaceEntity getInterfaceEntity(
            @WebParam(name = "projectCode", targetNamespace = "http://tempuri.org/")
                    String projectCode,
            @WebParam(name = "userName", targetNamespace = "http://tempuri.org/")
                    String userName,
            @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
                    String password,
            @WebParam(name = "instanceID", targetNamespace = "http://tempuri.org/")
                    String instanceID,
            @WebParam(name = "stepID", targetNamespace = "http://tempuri.org/")
                    String stepID
    );

    @WebMethod(operationName = "BatchInsertNewWFInstances", action = "http://tempuri.org/BatchInsertNewWFInstances")
    @RequestWrapper(localName = "BatchInsertNewWFInstances", targetNamespace = "http://tempuri.org/", className = "cn.com.scal.components.webservice.BatchInsertNewWFInstances")
    @ResponseWrapper(localName = "BatchInsertNewWFInstancesResponse", targetNamespace = "http://tempuri.org/", className = "cn.com.scal.components.webservice.BatchInsertNewWFInstancesResponse")
    @WebResult(name = "BatchInsertNewWFInstancesResult", targetNamespace = "http://tempuri.org/")
    public cn.com.scal.components.webservice.ArrayOfWFInterfaceEntity2 batchInsertNewWFInstances(
            @WebParam(name = "projectCode", targetNamespace = "http://tempuri.org/")
                    String projectCode,
            @WebParam(name = "userName", targetNamespace = "http://tempuri.org/")
                    String userName,
            @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
                    String password,
            @WebParam(name = "entitys", targetNamespace = "http://tempuri.org/")
                    cn.com.scal.components.webservice.ArrayOfWFInterfaceEntity2 entitys
    );

    @WebMethod(operationName = "BatchUpdateWFInstancesForTokenLogIn", action = "http://tempuri.org/BatchUpdateWFInstancesForTokenLogIn")
    @RequestWrapper(localName = "BatchUpdateWFInstancesForTokenLogIn", targetNamespace = "http://tempuri.org/", className = "cn.com.scal.components.webservice.BatchUpdateWFInstancesForTokenLogIn")
    @ResponseWrapper(localName = "BatchUpdateWFInstancesForTokenLogInResponse", targetNamespace = "http://tempuri.org/", className = "cn.com.scal.components.webservice.BatchUpdateWFInstancesForTokenLogInResponse")
    @WebResult(name = "BatchUpdateWFInstancesForTokenLogInResult", targetNamespace = "http://tempuri.org/")
    public cn.com.scal.components.webservice.ArrayOfString batchUpdateWFInstancesForTokenLogIn(
            @WebParam(name = "projectCode", targetNamespace = "http://tempuri.org/")
                    String projectCode,
            @WebParam(name = "userName", targetNamespace = "http://tempuri.org/")
                    String userName,
            @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
                    String password,
            @WebParam(name = "entitys", targetNamespace = "http://tempuri.org/")
                    cn.com.scal.components.webservice.ArrayOfWFInterfaceEntity2 entitys
    );

    @WebMethod(operationName = "GetInterfaceEntity2", action = "http://tempuri.org/GetInterfaceEntity2")
    @RequestWrapper(localName = "GetInterfaceEntity2", targetNamespace = "http://tempuri.org/", className = "cn.com.scal.components.webservice.GetInterfaceEntity2")
    @ResponseWrapper(localName = "GetInterfaceEntity2Response", targetNamespace = "http://tempuri.org/", className = "cn.com.scal.components.webservice.GetInterfaceEntity2Response")
    @WebResult(name = "GetInterfaceEntity2Result", targetNamespace = "http://tempuri.org/")
    public cn.com.scal.components.webservice.WFInterfaceEntity getInterfaceEntity2(
            @WebParam(name = "projectCode", targetNamespace = "http://tempuri.org/")
                    String projectCode,
            @WebParam(name = "userName", targetNamespace = "http://tempuri.org/")
                    String userName,
            @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
                    String password,
            @WebParam(name = "interfaceID", targetNamespace = "http://tempuri.org/")
                    String interfaceID
    );

    @WebMethod(operationName = "SetWFInstanceReadByInterfaceID", action = "http://tempuri.org/SetWFInstanceReadByInterfaceID")
    @RequestWrapper(localName = "SetWFInstanceReadByInterfaceID", targetNamespace = "http://tempuri.org/", className = "cn.com.scal.components.webservice.SetWFInstanceReadByInterfaceID")
    @ResponseWrapper(localName = "SetWFInstanceReadByInterfaceIDResponse", targetNamespace = "http://tempuri.org/", className = "cn.com.scal.components.webservice.SetWFInstanceReadByInterfaceIDResponse")
    @WebResult(name = "SetWFInstanceReadByInterfaceIDResult", targetNamespace = "http://tempuri.org/")
    public String setWFInstanceReadByInterfaceID(
            @WebParam(name = "projectCode", targetNamespace = "http://tempuri.org/")
                    String projectCode,
            @WebParam(name = "userName", targetNamespace = "http://tempuri.org/")
                    String userName,
            @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
                    String password,
            @WebParam(name = "interfaceID", targetNamespace = "http://tempuri.org/")
                    String interfaceID,
            @WebParam(name = "readTime", targetNamespace = "http://tempuri.org/")
                    String readTime
    );

    @WebMethod(operationName = "UpdateWFInstanceStatus", action = "http://tempuri.org/UpdateWFInstanceStatus")
    @RequestWrapper(localName = "UpdateWFInstanceStatus", targetNamespace = "http://tempuri.org/", className = "cn.com.scal.components.webservice.UpdateWFInstanceStatus")
    @ResponseWrapper(localName = "UpdateWFInstanceStatusResponse", targetNamespace = "http://tempuri.org/", className = "cn.com.scal.components.webservice.UpdateWFInstanceStatusResponse")
    @WebResult(name = "UpdateWFInstanceStatusResult", targetNamespace = "http://tempuri.org/")
    public String updateWFInstanceStatus(
            @WebParam(name = "projectCode", targetNamespace = "http://tempuri.org/")
                    String projectCode,
            @WebParam(name = "userName", targetNamespace = "http://tempuri.org/")
                    String userName,
            @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
                    String password,
            @WebParam(name = "instanceID", targetNamespace = "http://tempuri.org/")
                    String instanceID,
            @WebParam(name = "stepID", targetNamespace = "http://tempuri.org/")
                    String stepID,
            @WebParam(name = "user_ID_Consigned", targetNamespace = "http://tempuri.org/")
                    String userIDConsigned,
            @WebParam(name = "user_Name_Consigned", targetNamespace = "http://tempuri.org/")
                    String userNameConsigned,
            @WebParam(name = "readTime", targetNamespace = "http://tempuri.org/")
                    String readTime,
            @WebParam(name = "finishTime", targetNamespace = "http://tempuri.org/")
                    String finishTime
    );

    @WebMethod(operationName = "UpdateWFInstanceStatusByInterfaceID3", action = "http://tempuri.org/UpdateWFInstanceStatusByInterfaceID3")
    @RequestWrapper(localName = "UpdateWFInstanceStatusByInterfaceID3", targetNamespace = "http://tempuri.org/", className = "cn.com.scal.components.webservice.UpdateWFInstanceStatusByInterfaceID3")
    @ResponseWrapper(localName = "UpdateWFInstanceStatusByInterfaceID3Response", targetNamespace = "http://tempuri.org/", className = "cn.com.scal.components.webservice.UpdateWFInstanceStatusByInterfaceID3Response")
    @WebResult(name = "UpdateWFInstanceStatusByInterfaceID3Result", targetNamespace = "http://tempuri.org/")
    public String updateWFInstanceStatusByInterfaceID3(
            @WebParam(name = "projectCode", targetNamespace = "http://tempuri.org/")
                    String projectCode,
            @WebParam(name = "userName", targetNamespace = "http://tempuri.org/")
                    String userName,
            @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
                    String password,
            @WebParam(name = "interfaceID", targetNamespace = "http://tempuri.org/")
                    String interfaceID,
            @WebParam(name = "user_ID_Consigned", targetNamespace = "http://tempuri.org/")
                    String userIDConsigned,
            @WebParam(name = "user_Name_Consigned", targetNamespace = "http://tempuri.org/")
                    String userNameConsigned,
            @WebParam(name = "readTime", targetNamespace = "http://tempuri.org/")
                    String readTime,
            @WebParam(name = "finishTime", targetNamespace = "http://tempuri.org/")
                    String finishTime,
            @WebParam(name = "newFormUrl", targetNamespace = "http://tempuri.org/")
                    String newFormUrl,
            @WebParam(name = "newMobileFormUrl", targetNamespace = "http://tempuri.org/")
                    String newMobileFormUrl,
            @WebParam(name = "newInternetFormUrl", targetNamespace = "http://tempuri.org/")
                    String newInternetFormUrl
    );

    @WebMethod(operationName = "UpdateWFInstanceStatusByInterfaceID2", action = "http://tempuri.org/UpdateWFInstanceStatusByInterfaceID2")
    @RequestWrapper(localName = "UpdateWFInstanceStatusByInterfaceID2", targetNamespace = "http://tempuri.org/", className = "cn.com.scal.components.webservice.UpdateWFInstanceStatusByInterfaceID2")
    @ResponseWrapper(localName = "UpdateWFInstanceStatusByInterfaceID2Response", targetNamespace = "http://tempuri.org/", className = "cn.com.scal.components.webservice.UpdateWFInstanceStatusByInterfaceID2Response")
    @WebResult(name = "UpdateWFInstanceStatusByInterfaceID2Result", targetNamespace = "http://tempuri.org/")
    public String updateWFInstanceStatusByInterfaceID2(
            @WebParam(name = "projectCode", targetNamespace = "http://tempuri.org/")
                    String projectCode,
            @WebParam(name = "userName", targetNamespace = "http://tempuri.org/")
                    String userName,
            @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
                    String password,
            @WebParam(name = "interfaceID", targetNamespace = "http://tempuri.org/")
                    String interfaceID,
            @WebParam(name = "user_ID_Consigned", targetNamespace = "http://tempuri.org/")
                    String userIDConsigned,
            @WebParam(name = "user_Name_Consigned", targetNamespace = "http://tempuri.org/")
                    String userNameConsigned,
            @WebParam(name = "readTime", targetNamespace = "http://tempuri.org/")
                    String readTime,
            @WebParam(name = "finishTime", targetNamespace = "http://tempuri.org/")
                    String finishTime,
            @WebParam(name = "newFormUrl", targetNamespace = "http://tempuri.org/")
                    String newFormUrl
    );

    @WebMethod(operationName = "InsertNewWFInstanceByEntity2", action = "http://tempuri.org/InsertNewWFInstanceByEntity2")
    @RequestWrapper(localName = "InsertNewWFInstanceByEntity2", targetNamespace = "http://tempuri.org/", className = "cn.com.scal.components.webservice.InsertNewWFInstanceByEntity2")
    @ResponseWrapper(localName = "InsertNewWFInstanceByEntity2Response", targetNamespace = "http://tempuri.org/", className = "cn.com.scal.components.webservice.InsertNewWFInstanceByEntity2Response")
    @WebResult(name = "InsertNewWFInstanceByEntity2Result", targetNamespace = "http://tempuri.org/")
    public String insertNewWFInstanceByEntity2(
            @WebParam(name = "projectCode", targetNamespace = "http://tempuri.org/")
                    String projectCode,
            @WebParam(name = "userName", targetNamespace = "http://tempuri.org/")
                    String userName,
            @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
                    String password,
            @WebParam(name = "entity", targetNamespace = "http://tempuri.org/")
                    cn.com.scal.components.webservice.WFInterfaceEntity2 entity
    );

    @WebMethod(operationName = "UpdateWFInstanceStatusByEntity", action = "http://tempuri.org/UpdateWFInstanceStatusByEntity")
    @RequestWrapper(localName = "UpdateWFInstanceStatusByEntity", targetNamespace = "http://tempuri.org/", className = "cn.com.scal.components.webservice.UpdateWFInstanceStatusByEntity")
    @ResponseWrapper(localName = "UpdateWFInstanceStatusByEntityResponse", targetNamespace = "http://tempuri.org/", className = "cn.com.scal.components.webservice.UpdateWFInstanceStatusByEntityResponse")
    @WebResult(name = "UpdateWFInstanceStatusByEntityResult", targetNamespace = "http://tempuri.org/")
    public String updateWFInstanceStatusByEntity(
            @WebParam(name = "projectCode", targetNamespace = "http://tempuri.org/")
                    String projectCode,
            @WebParam(name = "userName", targetNamespace = "http://tempuri.org/")
                    String userName,
            @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
                    String password,
            @WebParam(name = "newEntity", targetNamespace = "http://tempuri.org/")
                    cn.com.scal.components.webservice.WFInterfaceEntity2 newEntity
    );

    @WebMethod(operationName = "DeleteEntity", action = "http://tempuri.org/DeleteEntity")
    @RequestWrapper(localName = "DeleteEntity", targetNamespace = "http://tempuri.org/", className = "cn.com.scal.components.webservice.DeleteEntity")
    @ResponseWrapper(localName = "DeleteEntityResponse", targetNamespace = "http://tempuri.org/", className = "cn.com.scal.components.webservice.DeleteEntityResponse")
    @WebResult(name = "DeleteEntityResult", targetNamespace = "http://tempuri.org/")
    public String deleteEntity(
            @WebParam(name = "projectCode", targetNamespace = "http://tempuri.org/")
                    String projectCode,
            @WebParam(name = "userName", targetNamespace = "http://tempuri.org/")
                    String userName,
            @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
                    String password,
            @WebParam(name = "instanceID", targetNamespace = "http://tempuri.org/")
                    String instanceID,
            @WebParam(name = "stepID", targetNamespace = "http://tempuri.org/")
                    String stepID
    );

    @WebMethod(operationName = "InsertNewWFInstanceByEntity", action = "http://tempuri.org/InsertNewWFInstanceByEntity")
    @RequestWrapper(localName = "InsertNewWFInstanceByEntity", targetNamespace = "http://tempuri.org/", className = "cn.com.scal.components.webservice.InsertNewWFInstanceByEntity")
    @ResponseWrapper(localName = "InsertNewWFInstanceByEntityResponse", targetNamespace = "http://tempuri.org/", className = "cn.com.scal.components.webservice.InsertNewWFInstanceByEntityResponse")
    @WebResult(name = "InsertNewWFInstanceByEntityResult", targetNamespace = "http://tempuri.org/")
    public String insertNewWFInstanceByEntity(
            @WebParam(name = "projectCode", targetNamespace = "http://tempuri.org/")
                    String projectCode,
            @WebParam(name = "userName", targetNamespace = "http://tempuri.org/")
                    String userName,
            @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
                    String password,
            @WebParam(name = "entity", targetNamespace = "http://tempuri.org/")
                    cn.com.scal.components.webservice.WFInterfaceEntity entity
    );

    @WebMethod(operationName = "SetWFInstanceRead", action = "http://tempuri.org/SetWFInstanceRead")
    @RequestWrapper(localName = "SetWFInstanceRead", targetNamespace = "http://tempuri.org/", className = "cn.com.scal.components.webservice.SetWFInstanceRead")
    @ResponseWrapper(localName = "SetWFInstanceReadResponse", targetNamespace = "http://tempuri.org/", className = "cn.com.scal.components.webservice.SetWFInstanceReadResponse")
    @WebResult(name = "SetWFInstanceReadResult", targetNamespace = "http://tempuri.org/")
    public String setWFInstanceRead(
            @WebParam(name = "projectCode", targetNamespace = "http://tempuri.org/")
                    String projectCode,
            @WebParam(name = "userName", targetNamespace = "http://tempuri.org/")
                    String userName,
            @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
                    String password,
            @WebParam(name = "instanceID", targetNamespace = "http://tempuri.org/")
                    String instanceID,
            @WebParam(name = "stepID", targetNamespace = "http://tempuri.org/")
                    String stepID,
            @WebParam(name = "readTime", targetNamespace = "http://tempuri.org/")
                    String readTime
    );

    @WebMethod(operationName = "DeleteEntity2", action = "http://tempuri.org/DeleteEntity2")
    @RequestWrapper(localName = "DeleteEntity2", targetNamespace = "http://tempuri.org/", className = "cn.com.scal.components.webservice.DeleteEntity2")
    @ResponseWrapper(localName = "DeleteEntity2Response", targetNamespace = "http://tempuri.org/", className = "cn.com.scal.components.webservice.DeleteEntity2Response")
    @WebResult(name = "DeleteEntity2Result", targetNamespace = "http://tempuri.org/")
    public String deleteEntity2(
            @WebParam(name = "projectCode", targetNamespace = "http://tempuri.org/")
                    String projectCode,
            @WebParam(name = "userName", targetNamespace = "http://tempuri.org/")
                    String userName,
            @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
                    String password,
            @WebParam(name = "interfaceID", targetNamespace = "http://tempuri.org/")
                    String interfaceID
    );

    @WebMethod(operationName = "UpdateWFInstanceStatusForTokenLogIn", action = "http://tempuri.org/UpdateWFInstanceStatusForTokenLogIn")
    @RequestWrapper(localName = "UpdateWFInstanceStatusForTokenLogIn", targetNamespace = "http://tempuri.org/", className = "cn.com.scal.components.webservice.UpdateWFInstanceStatusForTokenLogIn")
    @ResponseWrapper(localName = "UpdateWFInstanceStatusForTokenLogInResponse", targetNamespace = "http://tempuri.org/", className = "cn.com.scal.components.webservice.UpdateWFInstanceStatusForTokenLogInResponse")
    @WebResult(name = "UpdateWFInstanceStatusForTokenLogInResult", targetNamespace = "http://tempuri.org/")
    public String updateWFInstanceStatusForTokenLogIn(
            @WebParam(name = "projectCode", targetNamespace = "http://tempuri.org/")
                    String projectCode,
            @WebParam(name = "userName", targetNamespace = "http://tempuri.org/")
                    String userName,
            @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
                    String password,
            @WebParam(name = "newEntity", targetNamespace = "http://tempuri.org/")
                    cn.com.scal.components.webservice.WFInterfaceEntity2 newEntity
    );
}
